# =============================================
# Build config
# =============================================

root:           public
dest:           dist
assets:         assets
pages:          pages
data:           data
dataFile:       data.json

templates:      templates
includes:       <%= site.templates %>/partials/**.hbs
layouts:        <%= site.templates %>/layouts
layoutdefault:  default.hbs
layoutstatic:   shrstatic.hbs
dirNS:          shr
dirSHRFiles:    spec


# Extensions
helpers:
  - <%= site.templates %>/helpers/*.js

# =============================================
# Site metadata
# =============================================

description:      <%= pkg.description %>
